dasch-swiss/dsp-docs

.github/workflows/publish.yml
https://dasch.myjetbrains.com/youtrack/issue/DSP-251
=> Github action: Publish documentation on merge

README.md
- Replace `mkdocs` commands with `make` commands
- Add missing commands (clean, help)
=> Add Makefile command to README.md

.github/pull_request_template.md, docs/developers/dsp/contribution/index.md
resolves [DSP-761](https://dasch.myjetbrains.com/youtrack/issue/DSP-761)
Additional to the "update contribution" I added a Github PR template similar to all other main DSP repositories.
=> DPS-761 Update release process

docs/developers/dsp/contribution/index.md
=> Update release section in contribution

README.md, docs/developers/dsp/contribution/index.md
Updates the contribution documentation because of the integration from DSP-1168
=> DSP-1168 Update contribution documentation

docs/developers/dsp/contribution/index.md
=> docs(DSP-1189): PR title guideline and templates update

docs/developers/dsp/contribution/index.md
=> docs: update PR title guideline and templates (DSP-1189)

docs/developers/dsp/contribution/index.md
=> docs(contribution): pr title guideline and templates update (DSP-1189)

docs/developers/knora/getting-started.md
=> docs: add bazel instructions

docs/developers/dsp/contribution/index.md
=> docs(contribution): update documentation about the release process (DSP-1244)

docs/developers/dsp/contribution/index.md
=> docs(contribution): update contribution documentation (DSP-1383)

.github/workflows/main.yml, .gitmodules, Makefile, README.md
resolves DSP-1741
Here's the result: https://github.com/dasch-swiss/dsp-docs/actions/runs/938581406
=> fix(gh-ci): bug fix in deploy process (DSP-1741)

mkdocs.yml, overrides/main.html, overrides/partials/integrations/analytics/fathom.html
=> chore: add fathom

docs/index.md
=> fix: typo in link to DSP Tools (DSP-1780)

.github/workflows/main.yml
=> chore(gh-ci): run script only once a day

README.md
Update main README with Graphviz installation instruction
=> doc: Add graphviz installation instruction

README.md, docs/community/about-us.md, docs/community/product-updates.md, docs/developers/dsp/contribution/index.md, docs/index.md, mkdocs.yml
=> correct outdated stuff

docs/developers/getting-started.md, docs/index.md
=> update instructions how to get started (installation of your Mac) (DEV-2215)

release.mk
=> Update docs 2024.01.01

release.mk
=> Update docs 2024.02.01

.github/workflows/main.yml, Makefile
=> chore: bump dependencies in CI

.github/workflows/main.yml, .gitignore, Makefile, README.md, requirements.txt, update-and-deploy.sh
- **Use double quote to prevent globbing**
- **Generate openapi from dsp-ingest and dsp-api from release versions when building the documentation**
Needs:
- https://github.com/dasch-swiss/dsp-ingest/pull/219
- https://github.com/dasch-swiss/dsp-api/pull/3254
=> doc: Build openapi docs from release versions of dsp-api and dsp-ingest (DEV-3443)

.github/workflows/deploy.yml, .github/workflows/pr-checks.yml, Makefile, README.md
This PR solves the problem that the makefile assumes a virtual environment, but the CI works on the global python installation.
=> fix: fix venv issue in ci

release.mk
=> chore: DSP 2024.08.02

release.mk
=> deploy: bump docs to 2024.08.02

release.mk
=> chore: release 2024.09.01

release.mk
=> deploy: bump docs to 2025.01.01

release.mk
=> deploy: bump docs to 2025.02.01

release.mk
=> deploy: bump docs to 2025.02.03

release.mk
- **update versions**
- **Update submodules**
resolves DEV-
=> deploy: bump docs to 2025.03.02

release.mk
=> deploy: bump docs to 2025.05.01

release.mk
=> deploy: bump docs to 2025.06.01

release.mk
=> deploy: bump docs to 2025.08.01

.github/pull_request_template.md, .github/workflows/deploy.yml, .github/workflows/pr-checks.yml, .gitignore, Makefile, README.md, mkdocs.yml, update-and-deploy.sh
=> fix: remove openapi integration
